#pragma once


enum TokenType
{
	// Single-character tokens
	LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
	COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,
	COLON,

	// One or two character tokens
	BANG, BANG_EQUAL,
	EQUAL, EQUAL_EQUAL,
	GREATER, GREATER_EQUAL,
	LESS, LESS_EQUAL,

	// Preprocessor
	HASH,

	// Literals
	IDENTIFIER, STRING, NUMBER,

	// Keywords
	K_CLASS, K_CONST, K_STATIC,
	K_PUBLIC, K_PRIVATE,
	FOR, WHILE, IF, SWITCH,

	// Built in types
	T_INT, T_VOID, T_BOOL,

	// Reserved keywords for header tool
	MACRO_CLASS_DECL, MACRO_GEN_BODY,
	MACRO_FUNC_DECL, MACRO_PROP_DECL,

	END_OF_INTERNAL_TYPES,

	START_OF_CUSTOM_TYPES,
	END_OF_CUSTOM_TYPES = 1024,

	END_OF_FILE
};